language:
  - cpp

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - lcov

script:
  # Link gcc-7 and g++-7 to their standard commands
  - which gcc-7
  - which g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 1

  # Export CC and CXX to tell cmake which compiler to use
  - export CC=gcc-7
  - export CXX=g++-7

  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version

  # Trying to get python 3.6 
  - sudo apt update

  # Ninja and meson alternatives
  - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
  - sudo apt-get update
  - sudo apt-get install ninja-build

  # Lets see for meson
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt install python3.6
  - sudo apt install python3.6-dev
  - sudo apt install python3.6-venv
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python3.6 get-pip.py
  - sudo ln -s /usr/bin/python3.6 /usr/local/bin/python3
    #- sudo ln -s /usr/local/bin/pip /usr/local/bin/pip3
  - sudo pip install meson
  - sudo pip install cmake

  - sudo apt install libboost-all-dev
    #  Install Fuse 
    #- ( git clone https://github.com/libfuse/libfuse.git && mkdir -p libfuse/build &&
    #  cd libfuse/build &&  sudo meson .. && sudo ninja && sudo ninja install && cd - && sudo ldconfig )

  # Run your build commands next
  - ( cmake -G "Ninja" . && ninja && ninja test)
  - ( cd play_ctci_6_e ; make ; cd .. )
  
  
    #- sudo ./usdfs_test

after_success:
  - sudo lcov --capture --directory . --output-file coverage.info
  - sudo lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
  - sudo lcov --list coverage.info # debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

  - sudo ~/.local/bin/coveralls -r . -b .  --gcov-options '\-lp' 
  #- coveralls  

  
