all:
	make -s -C stack
	make -s -C queue
	make -s -C list
	make -s -C tree
	make -s -C graph

clean:
	make -s -C stack clean
	make -s -C queue clean
	make -s -C list clean
	make -s -C tree clean
	make -s -C graph clean
