dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
script:
  # Link gcc-7 and g++-7 to their standard commands
  - which gcc-7
  - which g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 1
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=gcc-7
  - export CXX=g++-7
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - ./build
after_success:
    - coveralls  -r . -b . --exclude public --exclude deps --gcov-options '\-lp'

